[package]
name = "ryo3-json"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "json ~ rust-python-json"

[dependencies]
pyo3 = { workspace = true, features = [] }
ryo3-bytes = { workspace = true }
ryo3-core = { workspace = true }
jiter = { workspace = true, features = ["serde"] }
ryo3-jiter = { workspace = true }
ryo3-serde = { workspace = true }
serde-transcode = { workspace = true }
lexical = { workspace = true }
lexical-core = { workspace = true }
itoa = { workspace = true }
serde_core = { workspace = true }
zmij = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
default = []
ry = []

[lints]
workspace = true
