[package]
name = "ryo3-json"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "json ~ rust-python-json"

[dependencies]
pyo3 = { workspace = true, features = [] }
ryo3-bytes = { workspace = true }
ryo3-core = { workspace = true }
ryo3-jiter = { workspace = true }
ryo3-serde = { workspace = true }
serde-transcode.workspace = true
serde_json.workspace = true
flexon = { path = "../../_flexon", optional = true, default-features = false, features = [
  "serde",
  "std",
] }
zmij = { version = "1.0", optional = true }
itoa = { version = "1.0", optional = true }
serde_core = { version = "1.0", optional = true, default-features = false }

[features]
default = ["experimental"]
experimental = ["dep:flexon", "dep:zmij", "dep:itoa", "dep:serde_core"]

[lints]
workspace = true
