[package]
name = "ryo3-std"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "rust-std python wrappers"

[dependencies]
bytes.workspace = true
pyo3 = { workspace = true, features = [] }
ryo3-bytes.workspace = true
ryo3-core.workspace = true
ryo3-macro-rules.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }
jiff = { workspace = true, optional = true }
ryo3-pydantic = { workspace = true, optional = true }

[features]
default = []
ry = [
  "dep:serde",
  "serde",
  "jiff",
  "std-time",
  "std-net",
  "std-fs",
  "std-process",
  "pydantic",
]
std-time = []
std-net = []
std-fs = []
std-process = []
pydantic = ["dep:ryo3-pydantic", "dep:jiff"]
serde = [
  "dep:serde",
  "jiff/serde",
]
jiff = ["dep:jiff"]

[lints]
workspace = true
