[package]
name = "ryo3-sqlformat"
description = "sql-formatter - wraps sqlformat (https://crates.io/crates/sqlformat)"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pyo3 = { workspace = true, features = ["experimental-inspect", "num-bigint"] }
sqlformat = "0.3.2"

[lints]
workspace = true
