[package]
name = "ryo3-bytes"
description = "ryo3 + bytes (https://docs.rs/regex/latest/bytes/)"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pyo3 = { workspace = true, features = ["experimental-inspect", "multiple-pymethods"] }
bytes = { workspace = true }
ahash = "0.8.11"

[lints]
workspace = true
