[package]
name = "ryo3-uuid"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "python + uuid (https://github.com/rust-lang/uuid)"

[dependencies]
pyo3 = { workspace = true, features = ["uuid", "serde"] }
ryo3-bytes.workspace = true
ryo3-macro-rules.workspace = true
serde = { workspace = true, optional = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "v8"] }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }

[features]
default = []
ry = [
  "serde",
]
serde = [
  "dep:serde",
  "uuid/serde",
]

[lints]
workspace = true
