[package]
name = "ryo3-shlex"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "python + rust-shlex (https://github.com/comex/rust-shlex)"

[dependencies]
pyo3 = { workspace = true, features = [] }
shlex.workspace = true

[lints]
workspace = true
