[package]
name = "ryo3-ulid"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "python + ulid crate (https://crates.io/crates/ulid)"

[dependencies]
pyo3 = { workspace = true, features = [] }
ryo3-pydantic = { workspace = true, features = [] }
ryo3-uuid.workspace = true
serde = { workspace = true, optional = true, features = ["derive"] }
ulid.workspace = true
uuid.workspace = true

[features]
default = []
ry = [
  "serde",
]
serde = [
  "dep:serde",
  "ulid/serde",
]

[lints]
workspace = true
