"""ry.ryo3.dev"""

from __future__ import annotations

import typing as t

# =============================================================================
# SUBPROCESS (VERY MUCH WIP)
# =============================================================================
def run(
    *args: str | list[str],
    capture_output: bool = True,
    input: bytes | None = None,
) -> t.Any: ...

# =============================================================================
# STRING-DEV
# =============================================================================

def anystr_noop(s: t.AnyStr) -> t.AnyStr: ...
def string_noop(s: str) -> str: ...
def bytes_noop(s: bytes) -> bytes: ...

# =============================================================================
# REQWEST
# =============================================================================

class AsyncClient:
    def __init__(self) -> None: ...
    async def get(self, url: str) -> Response: ...
    async def post(self, url: str) -> Response: ...
    async def put(self, url: str) -> Response: ...
    async def delete(self, url: str) -> Response: ...
    async def head(self, url: str) -> Response: ...

class Response:
    status_code: int
    headers: dict[str, str]

    async def text(self) -> str: ...
    async def json(self) -> t.Any: ...
    async def bytes(self) -> bytes: ...
    def bytes_stream(self) -> ResponseStream: ...

class ResponseStream:
    async def __aiter__(self) -> t.AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
