"""ryo3-dirs types"""

def audio_dir() -> str | None: ...
def cache_dir() -> str | None: ...
def config_dir() -> str | None: ...
def config_local_dir() -> str | None: ...
def data_dir() -> str | None: ...
def data_local_dir() -> str | None: ...
def desktop_dir() -> str | None: ...
def document_dir() -> str | None: ...
def download_dir() -> str | None: ...
def executable_dir() -> str | None: ...
def font_dir() -> str | None: ...
def home_dir() -> str | None: ...
def picture_dir() -> str | None: ...
def preference_dir() -> str | None: ...
def public_dir() -> str | None: ...
def runtime_dir() -> str | None: ...
def state_dir() -> str | None: ...
def template_dir() -> str | None: ...
def video_dir() -> str | None: ...
