"""ryo3-memchr types"""

from typing import TypeAlias

from ry._types import Buffer

Byte: TypeAlias = int | bytes

def memchr(needle: Byte, haystack: Buffer) -> int | None: ...
def memchr2(needle: Byte, needle2: Byte, haystack: Buffer) -> int | None: ...
def memchr3(
    needle: Byte, needle2: Byte, needle3: Byte, haystack: Buffer
) -> int | None: ...
def memrchr(needle: Byte, haystack: Buffer) -> int | None: ...
def memrchr2(needle: Byte, needle2: Byte, haystack: Buffer) -> int | None: ...
def memrchr3(
    needle: Byte, needle2: Byte, needle3: Byte, haystack: Buffer
) -> int | None: ...
