"""ryo3-memchr types"""

import typing as t

from ry._types import Buffer

_Byte: t.TypeAlias = int | bytes

def memchr(needle: _Byte, haystack: Buffer) -> int | None: ...
def memchr2(needle1: _Byte, needle2: _Byte, haystack: Buffer) -> int | None: ...
def memchr3(
    needle1: _Byte, needle2: _Byte, needle3: _Byte, haystack: Buffer
) -> int | None: ...
def memrchr(needle: _Byte, haystack: Buffer) -> int | None: ...
def memrchr2(needle1: _Byte, needle2: _Byte, haystack: Buffer) -> int | None: ...
def memrchr3(
    needle1: _Byte, needle2: _Byte, needle3: _Byte, haystack: Buffer
) -> int | None: ...
