"""ryo4-tokio types"""

import pathlib
import sys
import typing as t
from collections.abc import Generator
from types import TracebackType

from ry import Bytes
from ry._types import Buffer, FsPathLike, OpenBinaryMode
from ry.protocols import RyAsyncIterator, RyIterator
from ry.ryo3._std import FileReadStream, FileType, Metadata

if sys.version_info >= (3, 13):
    from warnings import deprecated
else:
    from typing_extensions import deprecated

# =============================================================================
# FS
# =============================================================================
async def canonicalize_async(path: FsPathLike) -> FsPathLike: ...
async def copy_async(src: FsPathLike, dst: FsPathLike) -> None: ...
async def create_dir_async(path: FsPathLike) -> None: ...
async def create_dir_all_async(path: FsPathLike) -> None: ...
async def hard_link_async(src: FsPathLike, dst: FsPathLike) -> None: ...
async def metadata_async(path: FsPathLike) -> None: ...
async def read_async(path: FsPathLike) -> Bytes: ...
async def remove_dir_async(path: FsPathLike) -> None: ...
async def remove_dir_all_async(path: FsPathLike) -> None: ...
async def remove_file_async(path: FsPathLike) -> None: ...
async def read_link_async(path: FsPathLike) -> FsPathLike: ...
async def read_to_string_async(path: FsPathLike) -> str: ...
async def rename_async(src: FsPathLike, dst: FsPathLike) -> None: ...
async def write_async(path: FsPathLike, buf: Buffer) -> None: ...
async def try_exists_async(path: FsPathLike) -> bool: ...
async def exists_async(path: FsPathLike) -> bool: ...

@t.final
class AsyncDirEntry:
    def __fspath__(self) -> str: ...
    @property
    def path(self) -> pathlib.Path: ...
    def basename(self) -> str: ...
    async def metadata(self) -> Metadata: ...
    async def file_type(self) -> FileType: ...

@t.final
class AsyncReadDir:
    """Async iterator for read_dir_async"""

    async def collect(self) -> list[AsyncDirEntry]: ...
    async def take(self, n: int) -> list[AsyncDirEntry]: ...
    def __aiter__(self) -> AsyncReadDir: ...
    async def __anext__(self) -> AsyncDirEntry: ...

async def read_dir_async(path: FsPathLike) -> AsyncReadDir: ...

# =============================================================================
# SLEEP
# =============================================================================
async def sleep_async(secs: float) -> float: ...
async def asleep(secs: float) -> float:
    """Alias for sleep_async"""

# =============================================================================
# ASYNC-FILE
# =============================================================================
@t.final
class AsyncFile:
    def __init__(
        self, path: FsPathLike, mode: OpenBinaryMode = "rb", buffering: int = -1
    ) -> None: ...
    async def close(self) -> None: ...
    async def flush(self) -> None: ...
    async def isatty(self) -> t.NoReturn: ...
    async def open(self) -> None: ...
    async def peek(self, size: int = ..., /) -> Bytes: ...
    async def read(self, size: int | None = None, /) -> Bytes: ...
    async def readable(self) -> bool: ...
    async def readall(self) -> Bytes: ...
    async def readline(self, size: int | None = None, /) -> Bytes: ...
    async def readlines(self, hint: int | None = None, /) -> list[Bytes]: ...
    async def seek(self, offset: int, whence: int = ..., /) -> int: ...
    async def seekable(self) -> bool: ...
    async def tell(self) -> int: ...
    async def truncate(self, pos: int | None = None, /) -> int: ...
    async def writable(self) -> bool: ...
    async def write(self, b: Buffer, /) -> int: ...
    @property
    def closed(self) -> bool: ...
    def __await__(self) -> Generator[t.Any, t.Any, t.Self]: ...
    def __aiter__(self) -> t.Self: ...
    async def __anext__(self) -> Bytes: ...
    async def __aenter__(self) -> t.Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

def aopen(
    path: FsPathLike, mode: OpenBinaryMode | str = "rb", buffering: int = -1
) -> AsyncFile: ...
@deprecated("`aiopen` is deprecated, use `aopen` instead")
def aiopen(
    path: FsPathLike, mode: OpenBinaryMode | str = "rb", buffering: int = -1
) -> AsyncFile: ...

@t.final
class AsyncFileReadStream(RyAsyncIterator[Bytes]):
    def __init__(
        self,
        path: FsPathLike,
        *,
        chunk_size: int = 65536,
        offset: int = 0,
        buffered: bool = True,
        strict: bool = True,
    ) -> None:
        """Return an AsyncFileReadStream

        Args:
            path: path-like object
            chunk_size: chunk size. Defaults to 65536.
            offset: offset to start reading from. Defaults to 0.
            buffered: whether the stream is buffered. Defaults to True.
            strict: whether to raise a ValueError on offset beyond EOF. Defaults to True.

        Raises:
            FileNotFoundError: If file does not exist.
            IsADirectoryError: If path is a directory.
            ValueError: If offset is beyond EOF and strict is True.

        """

    def __await__(self) -> Generator[t.Any, t.Any, t.Self]: ...
    def __aiter__(self) -> t.Self: ...
    async def __anext__(self) -> Bytes: ...
    async def collect(self) -> list[Bytes]: ...
    async def take(self, n: int = 1) -> list[Bytes]: ...

def read_stream_async(
    path: FsPathLike,
    chunk_size: int = 65536,
    *,
    offset: int = 0,
    buffered: bool = True,
    strict: bool = True,
) -> AsyncFileReadStream:
    """Return a FileReadStream

    Args:
        path: path-like object
        chunk_size: chunk size. Defaults to 65536.
        offset: offset to start reading from. Defaults to 0.
        buffered: whether the stream is buffered. Defaults to True.
        strict: whether to raise a ValueError on offset beyond EOF. Defaults to True.

    Raises:
        FileNotFoundError: If file does not exist.
        IsADirectoryError: If path is a directory.
        ValueError: If offset is beyond EOF and strict is True.

    """
