"""ryo3-uuid ~ types

based on typeshed types for python's builtin uuid module

REF: https://github.com/python/typeshed/blob/main/stdlib/uuid.pyi
"""

import builtins
import typing as t
import uuid as pyuuid

from ry._types import Buffer
from ry.protocols import FromStr

# Type aliases (_Bytes/_Int aliases `builtins.bytes`/`builtins.int`)
_Bytes: t.TypeAlias = builtins.bytes
_Int: t.TypeAlias = builtins.int
_V: t.TypeAlias = t.Literal[1, 2, 3, 4, 5, 6, 7, 8]
_UuidFields: t.TypeAlias = tuple[int, int, int, int, int, int]

@t.final
class UUID(FromStr):
    NAMESPACE_DNS: t.Final[UUID]
    NAMESPACE_URL: t.Final[UUID]
    NAMESPACE_OID: t.Final[UUID]
    NAMESPACE_X500: t.Final[UUID]
    NIL: t.Final[UUID]
    MAX: t.Final[UUID]
    RESERVED_NCS: t.Final = "reserved for NCS compatibility"
    RFC_4122: t.Final = "specified in RFC 4122"
    RESERVED_MICROSOFT: t.Final = "reserved for Microsoft compatibility"
    RESERVED_FUTURE: t.Final = "reserved for future definition"

    @t.overload
    def __new__(cls, hex: str, *, version: _V | None = None) -> t.Self: ...
    @t.overload
    def __new__(cls, *, bytes: _Bytes, version: _V | None = None) -> t.Self: ...
    @t.overload
    def __new__(cls, *, bytes_le: _Bytes, version: _V | None = None) -> t.Self: ...
    @t.overload
    def __new__(cls, *, fields: _UuidFields, version: _V | None = None) -> t.Self: ...
    @t.overload
    def __new__(cls, *, int: _Int, version: _V | None = None) -> t.Self: ...
    @t.overload
    def __new__(
        cls,
        hex: None = None,
        bytes: None = None,
        bytes_le: None = None,
        fields: None = None,
        int: None = None,
        version: _V | None = None,
    ) -> t.NoReturn: ...
    @staticmethod
    def getnode() -> _Int: ...
    @property
    def is_nil(self) -> bool: ...
    @property
    def bytes(self) -> _Bytes: ...
    @property
    def bytes_le(self) -> _Bytes: ...
    @property
    def clock_seq(self) -> _Int: ...
    @property
    def clock_seq_hi_variant(self) -> _Int: ...
    @property
    def clock_seq_low(self) -> _Int: ...
    @property
    def fields(self) -> _UuidFields: ...
    @property
    def hex(self) -> str: ...
    @property
    def int(self) -> _Int: ...
    @property
    def node(self) -> _Int: ...
    @property
    def time(self) -> _Int: ...
    @property
    def time_hi_version(self) -> _Int: ...
    @property
    def time_low(self) -> _Int: ...
    @property
    def time_mid(self) -> _Int: ...
    @property
    def urn(self) -> str: ...
    @property
    def variant(self) -> str: ...
    @property
    def version(self) -> t.Literal[1, 2, 3, 4, 5, 6, 7, 8] | None: ...
    def to_py(self) -> pyuuid.UUID: ...
    def to_string(self) -> str: ...
    # --- CLASSMETHODS --
    @classmethod
    def from_bytes(cls, b: _Bytes) -> t.Self: ...
    @classmethod
    def from_bytes_le(cls, b: _Bytes) -> t.Self: ...
    @classmethod
    def from_fields(cls, fields: _UuidFields) -> t.Self: ...
    @classmethod
    def from_hex(cls, hexstr: str) -> t.Self: ...
    @classmethod
    def from_int(cls, i: _Int) -> t.Self: ...
    @classmethod
    def from_pyuuid(cls, ob: pyuuid.UUID) -> t.Self: ...
    @classmethod
    def from_str(cls, s: str, /) -> t.Self: ...
    # --- DUNDERS ---
    def __bytes__(self) -> _Bytes: ...
    def __lt__(self, other: UUID) -> bool: ...
    def __le__(self, other: UUID) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __gt__(self, other: UUID) -> bool: ...
    def __ge__(self, other: UUID) -> bool: ...
    def __hash__(self) -> _Int: ...
    def __int__(self) -> _Int: ...

def getnode() -> _Int: ...
def uuid1(node: _Int | None = None, clock_seq: _Int | None = None) -> UUID: ...
def uuid3(namespace: UUID, name: str | _Bytes) -> UUID: ...
def uuid4() -> UUID: ...
def uuid5(namespace: UUID, name: str | _Bytes) -> UUID: ...
def uuid6(node: _Int | None = None, clock_seq: _Int | None = None) -> UUID: ...
def uuid7(timestamp: _Int | None = None) -> UUID: ...
@t.overload
def uuid8(*, buf: Buffer) -> UUID: ...  # 16 bytes buffer
@t.overload
def uuid8(
    a: _Int | None = None,
    b: _Int | None = None,
    c: _Int | None = None,
    *,
    buf: None = None,
) -> UUID: ...

NAMESPACE_DNS: t.Final[UUID]
NAMESPACE_URL: t.Final[UUID]
NAMESPACE_OID: t.Final[UUID]
NAMESPACE_X500: t.Final[UUID]
NIL: t.Final[UUID]
MAX: t.Final[UUID]
RESERVED_NCS: t.Final = "reserved for NCS compatibility"
RFC_4122: t.Final = "specified in RFC 4122"
RESERVED_MICROSOFT: t.Final = "reserved for Microsoft compatibility"
RESERVED_FUTURE: t.Final = "reserved for future definition"
