"""ryo3-walkdir types"""

import typing as t
from os import PathLike

from ry.protocols import RyIterator
from ry.ryo3._globset import Glob, GlobSet, Globster
from ry.ryo3._std import FileType, Metadata

@t.final
class WalkDirEntry:
    def to_string(self) -> str: ...
    def __fspath__(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def file_name(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def depth(self) -> int: ...
    @property
    def path_is_symlink(self) -> bool: ...
    @property
    def file_type(self) -> FileType: ...
    @property
    def is_dir(self) -> bool: ...
    @property
    def is_file(self) -> bool: ...
    @property
    def is_symlink(self) -> bool: ...
    @property
    def len(self) -> int: ...
    def __hash__(self) -> int: ...
    def __richcmp__(self, other: t.Self, op: int) -> bool: ...
    def metadata(self) -> Metadata: ...

@t.final
class WalkDirIter(RyIterator[WalkDirEntry]):
    """walkdir::Walkdir iterable wrapper"""
    def __new__(cls) -> t.NoReturn: ...
    def __iter__(self) -> t.Self: ...
    def __next__(self) -> WalkDirEntry: ...
    def collect(self) -> list[WalkDirEntry]: ...
    def take(self, n: int = 1) -> list[WalkDirEntry]: ...
    def next(self) -> WalkDirEntry: ...

def walkdir(
    path: str | PathLike[str] | None = None,
    /,
    *,
    files: bool = True,
    dirs: bool = True,
    contents_first: bool = False,
    min_depth: int = 0,
    max_depth: int | None = None,
    follow_links: bool = False,
    follow_root_links: bool = True,
    same_file_system: bool = False,
    sort_by_file_name: bool = False,
    glob: Glob | GlobSet | Globster | t.Sequence[str] | str | None = None,
) -> WalkDirIter: ...
