[package]
name = "ryo3-tokio-websockets"
version.workspace = true
authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description = "python + tokio-websockets crate (https://crates.io/crates/tokio-websockets)"

[dependencies]
pyo3 = { workspace = true, features = [] }
tokio-websockets = { workspace = true }

[lints]
workspace = true
